// <auto-generated />
using System;
using Infrastructure.Services.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddressCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddressPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BusinessAddress = "Antoon Van Osslaan 1, Bus 4",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1120"
                        },
                        new
                        {
                            ID = 2,
                            BusinessAddress = "KielStraat 1",
                            BusinessAddressCity = "Zeebrugge",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "8380"
                        },
                        new
                        {
                            ID = 3,
                            BusinessAddress = "Liège Science Park, Rue du Bois St-Jean, 15-17",
                            BusinessAddressCity = "Seraing",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "4102"
                        },
                        new
                        {
                            ID = 4,
                            BusinessAddress = "Quai des usines 16",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000"
                        },
                        new
                        {
                            ID = 5,
                            BusinessAddress = "Quai du Pont Canal 5",
                            BusinessAddressCity = "Strépy-Bracquegnies",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "7110"
                        },
                        new
                        {
                            ID = 6,
                            BusinessAddress = "Rue de Limbourg, 41B",
                            BusinessAddressCity = "Verviers",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "4800"
                        },
                        new
                        {
                            ID = 7,
                            BusinessAddress = "Rademakerstraat 8/4",
                            BusinessAddressCity = "Lissewege",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "8380"
                        },
                        new
                        {
                            ID = 8,
                            BusinessAddress = "Rue d'Ores",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000"
                        },
                        new
                        {
                            ID = 9,
                            BusinessAddress = "Rue de Vinçotte",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000"
                        },
                        new
                        {
                            ID = 10,
                            BusinessAddress = "Rue de Nestor",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000"
                        },
                        new
                        {
                            ID = 11,
                            BusinessAddress = "Rue du Lascentrum",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000"
                        },
                        new
                        {
                            ID = 12,
                            BusinessAddress = "Rue de Company",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000"
                        });
                });

            modelBuilder.Entity("Domain.Models.AllowedRegistrationType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableRegistrationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ExtendableStatus")
                        .HasColumnType("int");

                    b.Property<bool?>("HasPassed")
                        .HasColumnType("bit");

                    b.Property<int?>("RegistrationTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AvailableRegistrationTypeID");

                    b.HasIndex("RegistrationTypeID");

                    b.ToTable("AllowedRegistrationTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 0
                        },
                        new
                        {
                            ID = 2,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 0,
                            HasPassed = false,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 3,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 0,
                            HasPassed = false,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 4,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 0,
                            HasPassed = false,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 5,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 0,
                            HasPassed = false,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 6,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1
                        },
                        new
                        {
                            ID = 7,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = false,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 8,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = false,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 9,
                            AvailableRegistrationTypeID = 3,
                            ExtendableStatus = 1,
                            HasPassed = false,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 10,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = false,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 11,
                            AvailableRegistrationTypeID = 4,
                            ExtendableStatus = 1,
                            HasPassed = false,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 12,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = false,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 13,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 14,
                            AvailableRegistrationTypeID = 2,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 15,
                            AvailableRegistrationTypeID = 3,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 16,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 17,
                            AvailableRegistrationTypeID = 3,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 18,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 19,
                            AvailableRegistrationTypeID = 2,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 20,
                            AvailableRegistrationTypeID = 3,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 21,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 22,
                            AvailableRegistrationTypeID = 2,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 23,
                            AvailableRegistrationTypeID = 3,
                            ExtendableStatus = 1,
                            HasPassed = true,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 24,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2
                        },
                        new
                        {
                            ID = 25,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = false,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 26,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = false,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 27,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = false,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 28,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = false,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 29,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = true,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 30,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = true,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 31,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = true,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 32,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 2,
                            HasPassed = true,
                            RegistrationTypeID = 4
                        },
                        new
                        {
                            ID = 33,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 3
                        },
                        new
                        {
                            ID = 34,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 3,
                            HasPassed = true,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 35,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 3,
                            HasPassed = true,
                            RegistrationTypeID = 2
                        },
                        new
                        {
                            ID = 36,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 3,
                            HasPassed = true,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 37,
                            AvailableRegistrationTypeID = 1,
                            ExtendableStatus = 3,
                            HasPassed = true,
                            RegistrationTypeID = 4
                        });
                });

            modelBuilder.Entity("Domain.Models.AppSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxExpiryDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxExtensionDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxInAdvanceDays")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MaxExpiryDays = 365,
                            MaxExtensionDays = 270,
                            MaxInAdvanceDays = 30
                        });
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyMainPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebPage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressID = 1,
                            CompanyEmail = "info@v-c-l.be",
                            CompanyMainPhone = "+32 2 520 56 58",
                            CompanyName = "VCL",
                            WebPage = "v-c-l.be"
                        },
                        new
                        {
                            ID = 2,
                            AddressID = 2,
                            CompanyEmail = "info@tcz.be",
                            CompanyMainPhone = "+32 2 564 52 87",
                            CompanyName = "TCZ",
                            WebPage = "tcz.be"
                        },
                        new
                        {
                            ID = 3,
                            AddressID = 3,
                            CompanyEmail = "info@technifutur.be",
                            CompanyMainPhone = "+32 4 382 45 72",
                            CompanyName = "Technifutur",
                            WebPage = "technifutur.be"
                        },
                        new
                        {
                            ID = 4,
                            AddressID = 4,
                            CompanyEmail = "info@sibelga.be",
                            CompanyMainPhone = "+32 2 856 45 82",
                            CompanyName = "Sibelga Academy",
                            WebPage = "academy.sibelga.be"
                        },
                        new
                        {
                            ID = 5,
                            AddressID = 5,
                            CompanyEmail = "info@technocampus.be",
                            CompanyMainPhone = "+32 2 754 83 19",
                            CompanyName = "Technocampus",
                            WebPage = "technocampus.be"
                        },
                        new
                        {
                            ID = 6,
                            AddressID = 6,
                            CompanyEmail = "info@formation-polygone-eau.be",
                            CompanyMainPhone = "+32 8 778 93 30",
                            CompanyName = "Polygone de l'eau",
                            WebPage = "formation-polygone-eau.be"
                        },
                        new
                        {
                            ID = 7,
                            AddressID = 7,
                            CompanyEmail = "info@kcbrugge.be",
                            CompanyMainPhone = "+32 5 069 63 74",
                            CompanyName = "Kwalificatiecentrum Brugge bvba",
                            WebPage = "kcbrugge.be"
                        },
                        new
                        {
                            ID = 8,
                            AddressID = 8,
                            CompanyEmail = "info@ores.be",
                            CompanyMainPhone = "+32 2 683 57 32",
                            CompanyName = "Ores",
                            WebPage = "ores.be"
                        },
                        new
                        {
                            ID = 9,
                            AddressID = 9,
                            CompanyEmail = "info@vinçotte.be",
                            CompanyMainPhone = "+32 2 364 87 54",
                            CompanyName = "Vinçotte",
                            WebPage = "vinçotte.be"
                        },
                        new
                        {
                            ID = 10,
                            AddressID = 10,
                            CompanyEmail = "info@denestor.be",
                            CompanyMainPhone = "+32 9 375 31 69",
                            CompanyName = "De Nestor",
                            WebPage = "denestor.be"
                        },
                        new
                        {
                            ID = 11,
                            AddressID = 11,
                            CompanyEmail = "info@lascentrum.be",
                            CompanyMainPhone = "+32 2 954 74 85",
                            CompanyName = "Lascentrum",
                            WebPage = "lascentrum.be"
                        },
                        new
                        {
                            ID = 12,
                            AddressID = 12,
                            CompanyEmail = "info@hydrogaz.be",
                            CompanyMainPhone = "+32 2 456 81 37",
                            CompanyName = "Hydrogaz",
                            WebPage = "hydrogaz.be"
                        },
                        new
                        {
                            ID = 13,
                            AddressID = 12,
                            CompanyEmail = "info@fabricom.be",
                            CompanyMainPhone = "+32 2 793 98 07",
                            CompanyName = "Fabricom",
                            WebPage = "fabricom.be"
                        },
                        new
                        {
                            ID = 14,
                            AddressID = 12,
                            CompanyEmail = "info@ltc.be",
                            CompanyMainPhone = "+32 2 951 72 19",
                            CompanyName = "LTC",
                            WebPage = "ltc.be"
                        },
                        new
                        {
                            ID = 15,
                            AddressID = 12,
                            CompanyEmail = "info@verhoeven.be",
                            CompanyMainPhone = "+32 2 837 49 27",
                            CompanyName = "Verhoeven",
                            WebPage = "verhoeven.be"
                        },
                        new
                        {
                            ID = 16,
                            AddressID = 12,
                            CompanyEmail = "info@alkabel.be",
                            CompanyMainPhone = "+32 2 864 92 47",
                            CompanyName = "Alkabel",
                            WebPage = "alkabel.be"
                        },
                        new
                        {
                            ID = 17,
                            AddressID = 12,
                            CompanyEmail = "info@vindevogel.be",
                            CompanyMainPhone = "+32 2 482 24 35",
                            CompanyName = "Vindevogel",
                            WebPage = "vindevogel.be"
                        },
                        new
                        {
                            ID = 18,
                            AddressID = 12,
                            CompanyEmail = "info@canalco.be",
                            CompanyMainPhone = "+32 2 507 74 19",
                            CompanyName = "Canalco",
                            WebPage = "canalco.be"
                        },
                        new
                        {
                            ID = 19,
                            AddressID = 12,
                            CompanyEmail = "info@verschueren.be",
                            CompanyMainPhone = "+32 2 864 75 05",
                            CompanyName = "Verschueren",
                            WebPage = "verschueren.be"
                        },
                        new
                        {
                            ID = 20,
                            AddressID = 12,
                            CompanyEmail = "info@apc.be",
                            CompanyMainPhone = "+32 2 791 43 01",
                            CompanyName = "APC",
                            WebPage = "apc.be"
                        },
                        new
                        {
                            ID = 21,
                            AddressID = 12,
                            CompanyEmail = "info@fluvius.be",
                            CompanyMainPhone = "+32 2 907 43 67",
                            CompanyName = "Fluvius",
                            WebPage = "fluvius.be"
                        },
                        new
                        {
                            ID = 22,
                            AddressID = 12,
                            CompanyEmail = "info@infra.be",
                            CompanyMainPhone = "+32 2 703 09 84",
                            CompanyName = "Infra",
                            WebPage = "infra.be"
                        },
                        new
                        {
                            ID = 23,
                            AddressID = 12,
                            CompanyEmail = "info@dalcom.be",
                            CompanyMainPhone = "+32 2 378 50 04",
                            CompanyName = "Dalcom",
                            WebPage = "dalcom.be"
                        });
                });

            modelBuilder.Entity("Domain.Models.CompanyContact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("BusinessPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("ContactID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ContactID");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("CompanyContacts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressID = 1,
                            BusinessPhone = "+32 2 520 56 58",
                            CompanyID = 1,
                            ContactID = 1,
                            Email = "leen.dezillie@v-c-l.be ",
                            JobTitle = "Manager",
                            MobilePhone = "+32 486 64 45 52"
                        },
                        new
                        {
                            ID = 2,
                            AddressID = 5,
                            BusinessPhone = "+32 2 845 89 47",
                            CompanyID = 5,
                            ContactID = 2,
                            Email = "fabrice.vermeiren@technocampus.be",
                            JobTitle = "Manager",
                            MobilePhone = "+32 486 64 45 52"
                        },
                        new
                        {
                            ID = 3,
                            AddressID = 2,
                            BusinessPhone = "+32 5 050 08 29",
                            CompanyID = 2,
                            ContactID = 3,
                            Email = "koen@atriumopleidingen.be",
                            JobTitle = "Manager",
                            MobilePhone = "+32 496 56 87 24"
                        },
                        new
                        {
                            ID = 4,
                            BusinessPhone = "+32 2 274 39 09",
                            CompanyID = 4,
                            ContactID = 4,
                            Email = "academy-pe@sibelga.be",
                            JobTitle = "CEO",
                            MobilePhone = "+32 486 82 46 82"
                        });
                });

            modelBuilder.Entity("Domain.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(1985, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Leen",
                            LastName = "Dezillie"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(1977, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fabrice",
                            LastName = "Vermeiren"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(1984, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Koen",
                            LastName = "Nies"
                        },
                        new
                        {
                            ID = 4,
                            Birthday = new DateTime(1982, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bastien",
                            LastName = "De Spiegelaere"
                        });
                });

            modelBuilder.Entity("Domain.Models.ExamCenter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID")
                        .IsUnique();

                    b.ToTable("ExamCenters");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 9,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Domain.Models.Examination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamCenterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingCenterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ExamCenterID");

                    b.HasIndex("TrainingCenterID");

                    b.ToTable("Examinations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2021, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 1
                        },
                        new
                        {
                            ID = 2,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 7
                        },
                        new
                        {
                            ID = 3,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2021, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 3
                        },
                        new
                        {
                            ID = 4,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2021, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 2
                        },
                        new
                        {
                            ID = 5,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 6
                        },
                        new
                        {
                            ID = 6,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2022, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 4
                        },
                        new
                        {
                            ID = 7,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 8
                        },
                        new
                        {
                            ID = 8,
                            ExamCenterID = 1,
                            ExamDate = new DateTime(2023, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingCenterID = 5
                        });
                });

            modelBuilder.Entity("Domain.Models.ListExamCenter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyContactID")
                        .HasColumnType("int");

                    b.Property<int>("ExamCenterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyContactID")
                        .IsUnique();

                    b.HasIndex("ExamCenterID")
                        .IsUnique();

                    b.ToTable("ListExamCenter");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyContactID = 4,
                            ExamCenterID = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.ListTrainingCenter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyContactID")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCenterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyContactID")
                        .IsUnique();

                    b.HasIndex("TrainingCenterID")
                        .IsUnique();

                    b.ToTable("ListTrainingCenter");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyContactID = 1,
                            TrainingCenterID = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.PEPassport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AVNumber")
                        .HasColumnType("int");

                    b.Property<int>("PEWelderID")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCenterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PEWelderID");

                    b.HasIndex("TrainingCenterID");

                    b.ToTable("PEPassports");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AVNumber = 469,
                            PEWelderID = 1,
                            TrainingCenterID = 1
                        },
                        new
                        {
                            ID = 2,
                            AVNumber = 470,
                            PEWelderID = 2,
                            TrainingCenterID = 4
                        },
                        new
                        {
                            ID = 3,
                            AVNumber = 471,
                            PEWelderID = 3,
                            TrainingCenterID = 3
                        },
                        new
                        {
                            ID = 4,
                            AVNumber = 472,
                            PEWelderID = 4,
                            TrainingCenterID = 4
                        },
                        new
                        {
                            ID = 5,
                            AVNumber = 473,
                            PEWelderID = 5,
                            TrainingCenterID = 3
                        },
                        new
                        {
                            ID = 6,
                            AVNumber = 474,
                            PEWelderID = 6,
                            TrainingCenterID = 1
                        },
                        new
                        {
                            ID = 7,
                            AVNumber = 475,
                            PEWelderID = 7,
                            TrainingCenterID = 5
                        },
                        new
                        {
                            ID = 8,
                            AVNumber = 476,
                            PEWelderID = 8,
                            TrainingCenterID = 3
                        },
                        new
                        {
                            ID = 9,
                            AVNumber = 477,
                            PEWelderID = 9,
                            TrainingCenterID = 1
                        },
                        new
                        {
                            ID = 10,
                            AVNumber = 478,
                            PEWelderID = 10,
                            TrainingCenterID = 4
                        },
                        new
                        {
                            ID = 11,
                            AVNumber = 479,
                            PEWelderID = 11,
                            TrainingCenterID = 3
                        },
                        new
                        {
                            ID = 12,
                            AVNumber = 480,
                            PEWelderID = 12,
                            TrainingCenterID = 5
                        },
                        new
                        {
                            ID = 13,
                            AVNumber = 481,
                            PEWelderID = 13,
                            TrainingCenterID = 3
                        },
                        new
                        {
                            ID = 14,
                            AVNumber = 482,
                            PEWelderID = 14,
                            TrainingCenterID = 3
                        });
                });

            modelBuilder.Entity("Domain.Models.PEWelder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PEWelders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Nancy",
                            IdNumber = "452-3456789-84",
                            LastName = "Pelosi",
                            NationalNumber = "05.23.45-768-99"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Hillary",
                            IdNumber = "983-3456569-80",
                            LastName = "Clinton",
                            NationalNumber = "12.23.71-678-05"
                        },
                        new
                        {
                            ID = 3,
                            FirstName = "Donald",
                            IdNumber = "012-3456789-99",
                            LastName = "Trump",
                            NationalNumber = "01.23.45-678-99"
                        },
                        new
                        {
                            ID = 4,
                            FirstName = "Mike",
                            IdNumber = "634-6916789-85",
                            LastName = "Pence",
                            NationalNumber = "08.23.45-127-89"
                        },
                        new
                        {
                            ID = 5,
                            FirstName = "Sarah",
                            IdNumber = "834-3467289-85",
                            LastName = "Palin",
                            NationalNumber = "86.58.45-669-45"
                        },
                        new
                        {
                            ID = 6,
                            FirstName = "Ted",
                            IdNumber = "862-6386789-65",
                            LastName = "Cruz",
                            NationalNumber = "86.86.56-463-99"
                        },
                        new
                        {
                            ID = 7,
                            FirstName = "Elizabeth",
                            IdNumber = "853-5456783-85",
                            LastName = "Warren",
                            NationalNumber = "37.23.86-578-98"
                        },
                        new
                        {
                            ID = 8,
                            FirstName = "Bernie",
                            IdNumber = "682-6826789-54",
                            LastName = "Sanders",
                            NationalNumber = "92.23.58-638-83"
                        },
                        new
                        {
                            ID = 9,
                            FirstName = "Kamala",
                            IdNumber = "872-5256587-69",
                            LastName = "Harris",
                            NationalNumber = "55.63.45-856-63"
                        },
                        new
                        {
                            ID = 10,
                            FirstName = "Mitt",
                            IdNumber = "015-5256893-85",
                            LastName = "Romney",
                            NationalNumber = "63.98.45-682-63"
                        },
                        new
                        {
                            ID = 11,
                            FirstName = "Barack",
                            IdNumber = "512-8454289-95",
                            LastName = "Obama",
                            NationalNumber = "01.85.45-454-65"
                        },
                        new
                        {
                            ID = 12,
                            FirstName = "Andrew",
                            IdNumber = "082-3861789-08",
                            LastName = "Yang",
                            NationalNumber = "99.23.64-937-52"
                        },
                        new
                        {
                            ID = 13,
                            FirstName = "Joe",
                            IdNumber = "572-1447629-95",
                            LastName = "Biden",
                            NationalNumber = "88.98.45-893-63"
                        },
                        new
                        {
                            ID = 14,
                            FirstName = "Tulsi",
                            IdNumber = "052-5873789-57",
                            LastName = "Gabard",
                            NationalNumber = "28.23.48-689-63"
                        });
                });

            modelBuilder.Entity("Domain.Models.Process", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Processes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            ProcessName = "Electro"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            ProcessName = "Butt"
                        });
                });

            modelBuilder.Entity("Domain.Models.Registration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("ExaminationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HasPassed")
                        .HasColumnType("bit");

                    b.Property<int>("PEPassportID")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousRegistrationID")
                        .HasColumnType("int");

                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ExaminationID");

                    b.HasIndex("PEPassportID");

                    b.HasIndex("PreviousRegistrationID");

                    b.HasIndex("ProcessID");

                    b.HasIndex("RegistrationTypeID");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 12,
                            ExaminationID = 1,
                            ExpiryDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasPassed = true,
                            PEPassportID = 1,
                            ProcessID = 1,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 2,
                            CompanyID = 19,
                            ExaminationID = 1,
                            ExpiryDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasPassed = false,
                            PEPassportID = 9,
                            ProcessID = 2,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 3,
                            CompanyID = 13,
                            ExaminationID = 2,
                            ExpiryDate = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasPassed = true,
                            PEPassportID = 3,
                            ProcessID = 1,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 4,
                            CompanyID = 13,
                            ExaminationID = 3,
                            ExpiryDate = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PEPassportID = 3,
                            PreviousRegistrationID = 3,
                            ProcessID = 1,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 5,
                            CompanyID = 21,
                            ExaminationID = 2,
                            ExpiryDate = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PEPassportID = 11,
                            ProcessID = 2,
                            RegistrationTypeID = 1
                        },
                        new
                        {
                            ID = 6,
                            CompanyID = 21,
                            ExaminationID = 3,
                            ExpiryDate = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PEPassportID = 11,
                            PreviousRegistrationID = 5,
                            ProcessID = 2,
                            RegistrationTypeID = 3
                        },
                        new
                        {
                            ID = 7,
                            CompanyID = 23,
                            ExaminationID = 3,
                            ExpiryDate = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PEPassportID = 13,
                            ProcessID = 1,
                            RegistrationTypeID = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.RegistrationType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RegistrationTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            RegistrationTypeName = "Training"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            RegistrationTypeName = "Extension"
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            RegistrationTypeName = "Re-Examination1"
                        },
                        new
                        {
                            ID = 4,
                            IsActive = true,
                            RegistrationTypeName = "Re-Examination2"
                        });
                });

            modelBuilder.Entity("Domain.Models.Revoke", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyContactID")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyContactID");

                    b.HasIndex("RegistrationID")
                        .IsUnique();

                    b.ToTable("Revokes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Comment = "Inappropriate welding technique.",
                            CompanyContactID = 4,
                            RegistrationID = 5,
                            RevokeDate = new DateTime(2021, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Models.TrainingCenter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID")
                        .IsUnique();

                    b.HasIndex("Letter")
                        .IsUnique();

                    b.ToTable("TrainingCenters");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 1,
                            IsActive = true,
                            Letter = "V"
                        },
                        new
                        {
                            ID = 2,
                            CompanyID = 2,
                            IsActive = true,
                            Letter = "Z"
                        },
                        new
                        {
                            ID = 3,
                            CompanyID = 3,
                            IsActive = true,
                            Letter = "T"
                        },
                        new
                        {
                            ID = 4,
                            CompanyID = 5,
                            IsActive = true,
                            Letter = "S"
                        },
                        new
                        {
                            ID = 5,
                            CompanyID = 7,
                            IsActive = true,
                            Letter = "K"
                        },
                        new
                        {
                            ID = 6,
                            CompanyID = 10,
                            IsActive = true,
                            Letter = "N"
                        },
                        new
                        {
                            ID = 7,
                            CompanyID = 6,
                            IsActive = true,
                            Letter = "P"
                        },
                        new
                        {
                            ID = 8,
                            CompanyID = 11,
                            IsActive = true,
                            Letter = "L"
                        });
                });

            modelBuilder.Entity("Domain.Models.UIColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExtendableStatus")
                        .HasColumnType("int");

                    b.Property<bool?>("HasPassed")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("UIColors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ExtendableStatus = 0,
                            HasPassed = false
                        },
                        new
                        {
                            ID = 2,
                            Color = "table-success",
                            ExtendableStatus = 0,
                            HasPassed = true
                        },
                        new
                        {
                            ID = 3,
                            ExtendableStatus = 1,
                            HasPassed = false
                        },
                        new
                        {
                            ID = 4,
                            Color = "table-warning",
                            ExtendableStatus = 1,
                            HasPassed = true
                        },
                        new
                        {
                            ID = 5,
                            ExtendableStatus = 2,
                            HasPassed = false
                        },
                        new
                        {
                            ID = 6,
                            ExtendableStatus = 2,
                            HasPassed = true
                        },
                        new
                        {
                            ID = 7,
                            Color = "table-danger",
                            ExtendableStatus = 3,
                            HasPassed = false
                        },
                        new
                        {
                            ID = 8,
                            Color = "table-danger",
                            ExtendableStatus = 3,
                            HasPassed = true
                        });
                });

            modelBuilder.Entity("Domain.Models.UserToApprove", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddressCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddressPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyMainPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebPage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UsersToApprove");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(1990, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BusinessAddress = "Rue de John 10",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000",
                            BusinessPhone = "+32 2 165 45 85",
                            CompanyEmail = "info@v-c-l.be",
                            CompanyMainPhone = "+32 2 520 56 58",
                            CompanyName = "VCL",
                            Email = "john.doe@hotmail.com",
                            EmailConfirmed = true,
                            EmailLanguage = "en",
                            FirstName = "John",
                            JobTitle = "CEO",
                            LastName = "Doe",
                            MobilePhone = "+32 495 25 12 37",
                            WebPage = "v-c-l.be"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(1985, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BusinessAddress = "Rue d'Alice 16",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000",
                            BusinessPhone = "+32 2 634 72 81",
                            CompanyEmail = "info@sibelga.be",
                            CompanyMainPhone = "+32 2 856 45 82",
                            CompanyName = "Sibelga Academy",
                            Email = "alice.smith@hotmail.com",
                            EmailConfirmed = true,
                            EmailLanguage = "en",
                            FirstName = "Alice",
                            JobTitle = "CEO",
                            LastName = "Smith",
                            MobilePhone = "+32 482 93 71 09",
                            WebPage = "academy.sibelga.be"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(1975, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BusinessAddress = "Rue de James 60",
                            BusinessAddressCity = "Brussel",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "1000",
                            BusinessPhone = "+32 2 456 92 71",
                            CompanyEmail = "info@technifutur.be",
                            CompanyMainPhone = "+32 4 382 45 72",
                            CompanyName = "Technifutur",
                            Email = "james.bond@outlook.com",
                            EmailConfirmed = true,
                            EmailLanguage = "en",
                            FirstName = "James",
                            JobTitle = "CEO",
                            LastName = "Bond",
                            MobilePhone = "+32 457 76 24 82",
                            WebPage = "technifutur.be"
                        },
                        new
                        {
                            ID = 4,
                            Birthday = new DateTime(1996, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BusinessAddress = "Leopold III-lei 16",
                            BusinessAddressCity = "Edegem",
                            BusinessAddressCountry = "Belgium",
                            BusinessAddressPostalCode = "2650",
                            BusinessPhone = "+32 2 485 73 04",
                            CompanyEmail = "info@info.be",
                            CompanyMainPhone = "+32 3 230 05 28",
                            CompanyName = "Technifutur",
                            Email = "antoine.m1996@hotmail.com",
                            EmailConfirmed = true,
                            EmailLanguage = "nl",
                            FirstName = "Antoine",
                            JobTitle = "CEO",
                            LastName = "Moenaert",
                            MobilePhone = "+32 487 10 73 64",
                            WebPage = "info.be"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Models.AllowedRegistrationType", b =>
                {
                    b.HasOne("Domain.Models.RegistrationType", "AvailableRegistrationType")
                        .WithMany("PreviousRegistrationTypes")
                        .HasForeignKey("AvailableRegistrationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.RegistrationType", "RegistrationType")
                        .WithMany("AvailableRegistrationTypes")
                        .HasForeignKey("RegistrationTypeID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.HasOne("Domain.Models.Address", "Address")
                        .WithMany("Companies")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Models.CompanyContact", b =>
                {
                    b.HasOne("Domain.Models.Address", "Address")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Company", "Company")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Contact", "Contact")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Models.ExamCenter", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithOne("ExamCenter")
                        .HasForeignKey("Domain.Models.ExamCenter", "CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Examination", b =>
                {
                    b.HasOne("Domain.Models.ExamCenter", "ExamCenter")
                        .WithMany("Examinations")
                        .HasForeignKey("ExamCenterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TrainingCenter", "TrainingCenter")
                        .WithMany("Examinations")
                        .HasForeignKey("TrainingCenterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.ListExamCenter", b =>
                {
                    b.HasOne("Domain.Models.CompanyContact", "CompanyContact")
                        .WithOne("ListExamCenter")
                        .HasForeignKey("Domain.Models.ListExamCenter", "CompanyContactID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.ExamCenter", "ExamCenter")
                        .WithOne("ListExamCenter")
                        .HasForeignKey("Domain.Models.ListExamCenter", "ExamCenterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.ListTrainingCenter", b =>
                {
                    b.HasOne("Domain.Models.CompanyContact", "CompanyContact")
                        .WithOne("ListTrainingCenter")
                        .HasForeignKey("Domain.Models.ListTrainingCenter", "CompanyContactID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TrainingCenter", "TrainingCenter")
                        .WithOne("ListTrainingCenter")
                        .HasForeignKey("Domain.Models.ListTrainingCenter", "TrainingCenterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.PEPassport", b =>
                {
                    b.HasOne("Domain.Models.PEWelder", "PEWelder")
                        .WithMany("PEPassports")
                        .HasForeignKey("PEWelderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TrainingCenter", "TrainingCenter")
                        .WithMany("PEPassports")
                        .HasForeignKey("TrainingCenterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Registration", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithMany("Registrations")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Examination", "Examination")
                        .WithMany("Registrations")
                        .HasForeignKey("ExaminationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.PEPassport", "PEPassport")
                        .WithMany("Registrations")
                        .HasForeignKey("PEPassportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Registration", "PreviousRegistration")
                        .WithMany()
                        .HasForeignKey("PreviousRegistrationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Process", "Process")
                        .WithMany("Registrations")
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.RegistrationType", "RegistrationType")
                        .WithMany()
                        .HasForeignKey("RegistrationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Revoke", b =>
                {
                    b.HasOne("Domain.Models.CompanyContact", "CompanyContact")
                        .WithMany("Revokes")
                        .HasForeignKey("CompanyContactID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Registration", "Registration")
                        .WithOne("Revoke")
                        .HasForeignKey("Domain.Models.Revoke", "RegistrationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.TrainingCenter", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithOne("TrainingCenter")
                        .HasForeignKey("Domain.Models.TrainingCenter", "CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
